/* * V1: Script inicial para criar a tabela de transações
 */

CREATE TABLE transactions (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        description   VARCHAR(255) NOT NULL,
        amount        DOUBLE PRECISION NOT NULL,
        date          DATE NOT NULL,
        type          VARCHAR(30) NOT NULL,

    -- Garante que o 'type' só possa ser INCOME ou EXPENSE
        CONSTRAINT chk_type CHECK (type IN ('INCOME', 'EXPENSE'))
);